CREATE SCHEMA STAND
GO

CREATE TABLE STAND.TIPO_VEICULO(
	Veiculo_ID		INT NOT NULL,
	Designação		VARCHAR(50) NOT NULL,
	PRIMARY KEY(Veiculo_ID),
);

CREATE TABLE STAND.TIPO_PECA(
	TipoPeca_ID		INT NOT NULL,
	Designação		VARCHAR(50) NOT NULL,
	PRIMARY KEY(TipoPeca_ID),
);

CREATE TABLE STAND.PECAS(
	Peca_ID			INT NOT NULL IDENTITY(1,1),
	Fabricante		VARCHAR(20),
	Disponibilidade	BIT NOT NULL,
	Tipo_Peca		INT NOT NULL,
	Nome 			VARCHAR(50) NOT NULL,
	PRIMARY KEY(Peca_ID),
	FOREIGN KEY(Tipo_Peca) REFERENCES STAND.TIPO_PECA(TipoPeca_ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
);

CREATE TABLE STAND.STAND(
	Stand_ID	INT NOT NULL,
	Nome		VARCHAR(20) NOT NULL,
	Localizacao	VARCHAR(30)	NOT NULL,
	Contacto	VARCHAR(9) NOT NULL,
	Website		VARCHAR(50),
	PRIMARY KEY(Stand_ID)
);

CREATE TABLE STAND.OFICINA(
	Oficina_ID		INT NOT NULL,
	Nome			VARCHAR(20) NOT NULL,
	Contacto		VARCHAR(9) NOT NULL,
	Localizacao		VARCHAR(30)	NOT NULL,
	PRIMARY KEY(Oficina_ID)
);

CREATE TABLE STAND.CLIENTE(
	Nome		VARCHAR(40) NOT NULL,
	NIF			CHAR(9)	NOT NULL,
	Morada		VARCHAR(30),
	Contacto	CHAR(9)	NOT NULL,
	Nr_Cliente	INT	NOT NULL IDENTITY(1,1),
	PRIMARY KEY(Nr_Cliente)
);

CREATE TABLE STAND.MECANICO(
	Nome			VARCHAR(40) NOT NULL,
	NIF				CHAR(9)	NOT NULL,
	Morada			VARCHAR(30),
	Contacto		CHAR(9)	NOT NULL,
	Nr_Funcionario	INT	NOT NULL IDENTITY(1,1),
	Oficina_ID 		INT,
	PRIMARY KEY(Nr_Funcionario),
	FOREIGN KEY(Oficina_ID) REFERENCES STAND.OFICINA(Oficina_ID)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE STAND.VEICULO_REPARAR(
	Chassis_ID		INT NOT NULL,
	Marca			VARCHAR(15) NOT NULL,
	Modelo			VARCHAR(30) NOT NULL,
	Quilometragem	INT,
	Estado			BIT NOT NULL,
	Tipo_Veiculo	INT NOT NULL,
	Peca_ID			INT,
	Oficina_ID		INT,
	Mecanico 		INT,
	PRIMARY KEY(Chassis_ID),
	FOREIGN KEY(Tipo_Veiculo) REFERENCES STAND.TIPO_VEICULO(Veiculo_ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(Peca_ID) REFERENCES STAND.PECAS(Peca_ID)
	ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY(Oficina_ID) REFERENCES STAND.OFICINA(Oficina_ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(Mecanico) REFERENCES STAND.MECANICO(Nr_Funcionario)
);

CREATE TABLE STAND.VEICULO_VENDA(
	Chassis_ID		INT NOT NULL,
	Marca			VARCHAR(15) NOT NULL,
	Modelo			VARCHAR(30) NOT NULL,
	Quilometragem	INT,
	Pais_Origem		VARCHAR(30),
	Ano_Fabrico		CHAR(4),
	Combustivel		VARCHAR(10) NOT NULL,
	Tracao			VARCHAR(10),
	Tipo_Veiculo	INT NOT NULL,
	Potencia 		INT,
	Stand_ID		INT NOT NULL,
	PRIMARY KEY(Chassis_ID),
	FOREIGN KEY(Tipo_Veiculo) REFERENCES STAND.TIPO_VEICULO(Veiculo_ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(Stand_ID) REFERENCES STAND.STAND(Stand_ID)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE STAND.LEVA(
	Data_Entrega	Date,
	Veiculo_ID		INT NOT NULL,
	Cliente_ID		INT NOT NULL,
	PRIMARY KEY(Veiculo_ID, Cliente_ID),
	FOREIGN KEY(Veiculo_ID) REFERENCES STAND.VEICULO_REPARAR(Chassis_ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(Cliente_ID) REFERENCES STAND.CLIENTE(Nr_Cliente)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE STAND.COMPRA(
	Transacao_ID	INT NOT NULL IDENTITY(1,1),
	Preço			INT	NOT NULL,
	Stand_ID 		INT NOT NULL,
	Veiculo_ID 		INT NOT NULL,
	PRIMARY KEY(Transacao_ID),
	FOREIGN KEY(Stand_ID) REFERENCES STAND.STAND(Stand_ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(Veiculo_ID) REFERENCES STAND.VEICULO_VENDA(Chassis_ID)
);

CREATE TABLE STAND.FAZ(
	Transacao	INT 	NOT NULL,
	Cliente		INT 	NOT NULL,
	Data_Compra	Date,
	PRIMARY KEY(Transacao),
	FOREIGN KEY(Transacao) REFERENCES STAND.COMPRA(Transacao_ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(Cliente) REFERENCES STAND.CLIENTE(Nr_Cliente)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE STAND.VEICULOS_REPARADOS(
	Chassis_ID		INT NOT NULL,
	Marca			VARCHAR(15) NOT NULL,
	Modelo			VARCHAR(30) NOT NULL,
	Quilometragem	INT,
	Tipo_Veiculo	INT NOT NULL,
	Peca_ID			INT,
	Oficina_ID		INT,
	Cliente_ID		INT NOT NULL,
	PRIMARY KEY(Chassis_ID),
	FOREIGN KEY(Tipo_Veiculo) REFERENCES STAND.TIPO_VEICULO(Veiculo_ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(Peca_ID) REFERENCES STAND.PECAS(Peca_ID)
	ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY(Oficina_ID) REFERENCES STAND.OFICINA(Oficina_ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(Cliente_ID) REFERENCES STAND.CLIENTE(Nr_Cliente)
	ON DELETE CASCADE
);

CREATE TABLE STAND.VEICULOS_CLIENTES(
	Chassis_ID		INT NOT NULL,
	Marca			VARCHAR(15) NOT NULL,
	Modelo			VARCHAR(30) NOT NULL,
	Quilometragem	INT,
	Pais_Origem		VARCHAR(30),
	Ano_Fabrico		CHAR(4),
	Combustivel		VARCHAR(10) NOT NULL,
	Tracao			VARCHAR(10),
	Tipo_Veiculo	INT NOT NULL,
	Potencia 		INT,
	Stand_ID		INT NOT NULL,
	Cliente_ID		INT NOT NULL,
	PRIMARY KEY(Chassis_ID),
	FOREIGN KEY(Tipo_Veiculo) REFERENCES STAND.TIPO_VEICULO(Veiculo_ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(Stand_ID) REFERENCES STAND.STAND(Stand_ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(Cliente_ID) REFERENCES STAND.CLIENTE(Nr_Cliente)
	ON DELETE CASCADE ON UPDATE CASCADE
);