CREATE SCHEMA CONFERENCES
GO

CREATE TABLE CONFERENCES.INSTITUIÇÃO(
	Nome VARCHAR(20) NOT NULL,
	Endereço VARCHAR(20) NOT NULL,
	PRIMARY KEY(Endereço)
);

CREATE TABLE CONFERENCES.AUTOR(
	Email VARCHAR(20) NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Endereço_Instituição VARCHAR(20) NOT NULL,
	PRIMARY KEY(Email),
	FOREIGN KEY(Endereço_Instituição) REFERENCES CONFERENCES.INSTITUIÇÃO(Endereço)
);

CREATE TABLE CONFERENCES.ESTUDANTE(
	Email VARCHAR(20) NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Endereço_Instituição VARCHAR(20) NOT NULL,
	Morada VARCHAR(20),
	DataInscrição Date,
	Comprovativo VARCHAR(20),
	PRIMARY KEY(Email),
	FOREIGN KEY(Endereço_Instituição) REFERENCES CONFERENCES.INSTITUIÇÃO(Endereço)
);

CREATE TABLE CONFERENCES.NAO_ESTUDANTE(
	Email VARCHAR(20) NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Endereço_Instituição VARCHAR(20) NOT NULL,
	Morada VARCHAR(20),
	DataInscrição Date,
	ReferenciaEletronica VARCHAR(50),
	PRIMARY KEY(Email),
	FOREIGN KEY(Endereço_Instituição) REFERENCES CONFERENCES.INSTITUIÇÃO(Endereço)
);

CREATE TABLE CONFERENCES.ARTIGO(
	NumRegisto INT NOT NULL,
	Titulo VARCHAR(30) NOT NULL,
	PRIMARY KEY(NumRegisto)
);

CREATE TABLE CONFERENCES.TEM(
	NumRegisto INT,
	Email VARCHAR(20) NOT NULL,
	PRIMARY KEY(NumRegisto,Email),
	FOREIGN KEY(NumRegisto) REFERENCES CONFERENCES.ARTIGO(NumRegisto),
	FOREIGN KEY(Email) REFERENCES CONFERENCES.AUTOR(Email)
);