CREATE SCHEMA STOCKS
GO

CREATE TABLE STOCKS.PRODUTO(
	Codigo_Produto INT NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Preço MONEY NOT NULL,
	IVA INT NOT NULL,
	PRIMARY KEY(Codigo_Produto)
);

CREATE TABLE STOCKS.TIPO_FORNECEDOR(
	Codigo_Fornecedor INT NOT NULL,
	Designação VARCHAR(50),
	PRIMARY KEY(Codigo_Fornecedor)
);

CREATE TABLE STOCKS.FORNECEDOR(
	NIF INT NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Metodo_Pagamento VARCHAR(50),
	Endereço VARCHAR(50),
	Nr_Fax INT,
	Cod_Fornecedor INT NOT NULL,
	PRIMARY KEY(NIF),
	FOREIGN KEY(Cod_Fornecedor) REFERENCES STOCKS.TIPO_FORNECEDOR(Codigo_Fornecedor),
);

CREATE TABLE STOCKS.ENCOMENDA(
	Nr_Encomenda VARCHAR(10) NOT NULL,
	DataEncomenda Date,
	NIF INT NOT NULL,
	PRIMARY KEY(Nr_Encomenda),
	FOREIGN KEY(NIF) REFERENCES STOCKS.FORNECEDOR(NIF)
);

CREATE TABLE STOCKS.TEM(
	Produto INT NOT NULL,
	Nr_Encomenda VARCHAR(10) NOT NULL,
	PRIMARY KEY(Produto),
	FOREIGN KEY(Nr_Encomenda) REFERENCES STOCKS.ENCOMENDA(Nr_Encomenda),
	FOREIGN KEY(Produto) REFERENCES STOCKS.PRODUTO(Codigo_Produto),
);