-- CREATE SCHEMA RENTCAR
-- GO

CREATE TABLE RENTCAR.CLIENTE(
	NIF INT IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(50),
	Endereço VARCHAR(50),
	Num_carta VARCHAR(10) NOT NULL,
);

CREATE TABLE RENTCAR.BALCAO(
	Numero INT NOT NULL,
	Nome VARCHAR(50), 
	Endereço VARCHAR(50),
	PRIMARY KEY(Numero)
);

CREATE TABLE RENTCAR.TIPO_VEICULO(
	Codigo INT NOT NULL,
	Designação VARCHAR(20),
	ArCondicionado VARCHAR(4),
	PRIMARY KEY(Codigo),
);

CREATE TABLE RENTCAR.VEICULO(
	Matricula VARCHAR(10) NOT NULL,
	Marca VARCHAR(20),
	Ano VARCHAR(4),
	Tipo_Veiculo INT NOT NULL,
	PRIMARY KEY(Matricula),
	FOREIGN KEY(Tipo_Veiculo) REFERENCES RENTCAR.TIPO_VEICULO(Codigo)
);

CREATE TABLE RENTCAR.LIGEIRO(
	Codigo_Tipo INT NOT NULL,
	Portas INT,
	NumLugares INT,
	Combustivel VARCHAR(10),
	PRIMARY KEY(Codigo_Tipo),
	FOREIGN KEY(Codigo_Tipo) REFERENCES RENTCAR.TIPO_VEICULO(Codigo)
);

CREATE TABLE RENTCAR.PESADO(
	Codigo_Tipo INT NOT NULL,
	Peso INT,
	Passageiros INT NOT NULL,
	PRIMARY KEY(Codigo_Tipo),
	FOREIGN KEY(Codigo_Tipo) REFERENCES RENTCAR.TIPO_VEICULO(Codigo)
);

CREATE TABLE RENTCAR.SIMILARIDADE(
	Codigo1 INT NOT NULL,
	Codigo2 INT NOT NULL,
	FOREIGN KEY(Codigo1) REFERENCES RENTCAR.TIPO_VEICULO(Codigo),
	FOREIGN KEY(Codigo2) REFERENCES RENTCAR.TIPO_VEICULO(Codigo)
);

CREATE TABLE RENTCAR.ALUGUER(
	Nr_aluguer INT NOT NULL,
	Duração TIME,
	DataAluguer DATE,
	NIF_Cliente INT NOT NULL,
	Nr_Balcão INT NOT NULL,
	Matricula VARCHAR(10) NOT NULL,
	PRIMARY KEY(Nr_aluguer),
	FOREIGN KEY(NIF_Cliente) REFERENCES RENTCAR.CLIENTE(NIF),
	FOREIGN KEY(Nr_Balcão) REFERENCES RENTCAR.BALCAO(Numero),
	FOREIGN KEY(Matricula) REFERENCES RENTCAR.VEICULO(Matricula) 
);