CREATE SCHEMA STOCKS
GO

CREATE TABLE STOCKS.PRODUTO(
	Codigo_Produto INT NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Preço MONEY,
	IVA INT,
	Unidades INT, 
	PRIMARY KEY(Codigo_Produto)
);

CREATE TABLE STOCKS.TIPO_FORNECEDOR(
	Codigo_Fornecedor INT NOT NULL,
	Designação VARCHAR(50),
	PRIMARY KEY(Codigo_Fornecedor)
);

CREATE TABLE STOCKS.FORNECEDOR(
	NIF INT NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Fax INT,
	Endereço VARCHAR(50),
	Metodo_Pagamento VARCHAR(50),
	Cod_Fornecedor INT NOT NULL,
	PRIMARY KEY(NIF),
	FOREIGN KEY(Cod_Fornecedor) REFERENCES STOCKS.TIPO_FORNECEDOR(Codigo_Fornecedor),
);

CREATE TABLE STOCKS.ENCOMENDA(
	Nr_Encomenda VARCHAR(10) NOT NULL,
	DataEncomenda Date,
	Fornecedor INT NOT NULL,
	PRIMARY KEY(Nr_Encomenda),
	FOREIGN KEY(Fornecedor) REFERENCES STOCKS.FORNECEDOR(NIF)
);

CREATE TABLE STOCKS.ITEM(
	Nr_Encomenda VARCHAR(10) NOT NULL,
	Produto INT NOT NULL,
	Unidades INT,
	PRIMARY KEY(Produto),
	FOREIGN KEY(Nr_Encomenda) REFERENCES STOCKS.ENCOMENDA(Nr_Encomenda),
	FOREIGN KEY(Produto) REFERENCES STOCKS.PRODUTO(Codigo_Produto),
);