CREATE SCHEMA  PRESCRIÇAO_MEDICAMENTOS
go


CREATE TABLE PRESCRIÇAO_MEDICAMENTOS.MEDICO (
	n_medico		INT,
	nome			VARCHAR(30) NOT NULL,
	especialidade	VARCHAR(30),
	PRIMARY KEY(n_medico)
);


CREATE TABLE PRESCRIÇAO_MEDICAMENTOS.PACIENTE (
	n_utente			INT,
	nome				VARCHAR(30) NOT NULL,
	data_nascimento		DATE NOT NULL,
	endereço			VARCHAR(30),
	PRIMARY KEY(n_utente)
);


CREATE TABLE PRESCRIÇAO_MEDICAMENTOS.FARMACIA (
	nome		VARCHAR(30) NOT NULL,
	endereço	VARCHAR(30),
	telefone	INT,
	PRIMARY KEY(nome)
);

CREATE TABLE PRESCRIÇAO_MEDICAMENTOS.PRESCRIÇAO (
	n_prescricao	INT,
	n_medico		INT,
	n_utente		INT,
	data_presc		DATE,
	nome_farmacia	VARCHAR(30),
	PRIMARY KEY(n_prescricao),
	FOREIGN KEY(n_medico) REFERENCES PRESCRIÇAO_MEDICAMENTOS.MEDICO(n_medico),
	FOREIGN KEY(n_utente) REFERENCES PRESCRIÇAO_MEDICAMENTOS.PACIENTE(n_utente),
	FOREIGN KEY(nome_farmacia) REFERENCES PRESCRIÇAO_MEDICAMENTOS.FARMACIA(nome)
);
/*
ALTER TABLE PRESCRIÇAO_MEDICAMENTOS.PRESCRIÇAO
ALTER COLUMN data_presc DATE;
*/
CREATE TABLE PRESCRIÇAO_MEDICAMENTOS.FARMACEUTICA (
	n_registo	INT,
	nome		VARCHAR(50) NOT NULL,
	endereco	VARCHAR(100) NOT NULL,
	PRIMARY KEY(n_registo),
);
/*
DROP TABLE PRESCRIÇAO_MEDICAMENTOS.FARMACEUTICA;

ALTER TABLE PRESCRIÇAO_MEDICAMENTOS.FARMACEUTICA
ALTER COLUMN endereco VARCHAR (100) NOT NULL;
*/
CREATE TABLE PRESCRIÇAO_MEDICAMENTOS.FARMACO (
	nome_comercial	VARCHAR(150) NOT NULL,
	formula			VARCHAR(30),
	n_registo_farm	INT,
	PRIMARY KEY(n_registo_farm, nome_comercial),
	FOREIGN KEY(n_registo_farm) REFERENCES PRESCRIÇAO_MEDICAMENTOS.FARMACEUTICA(n_registo)
);
/*
 SELECT name AS 'Foreign Key Constraint Name', 
	       OBJECT_SCHEMA_NAME(parent_object_id) + '.' + OBJECT_NAME(parent_object_id) AS 'Child Table'
   FROM sys.foreign_keys 
   WHERE OBJECT_SCHEMA_NAME(referenced_object_id) = 'PRESCRIÇAO_MEDICAMENTOS' AND 
              OBJECT_NAME(referenced_object_id) = 'FARMACEUTICA';
ALTER TABLE PRESCRIÇAO_MEDICAMENTOS.FARMACO 
ALTER COLUMN nome_comercial VARCHAR(150) NOT NULL;
ALTER TABLE PRESCRIÇAO_MEDICAMENTOS.FARMACO DROP CONSTRAINT FK__FARMACO__nome_co__59C55456;
DROP TABLE PRESCRIÇAO_MEDICAMENTOS.CONTEM;
DROP TABLE PRESCRIÇAO_MEDICAMENTOS.FARMACO;
*/

CREATE TABLE PRESCRIÇAO_MEDICAMENTOS.CONTEM (
	n_prescricao	INT,
	n_registo		INT,
	nome_comercial	VARCHAR(150),
	PRIMARY KEY(n_prescricao, n_registo, nome_comercial),
	FOREIGN KEY(n_prescricao) REFERENCES PRESCRIÇAO_MEDICAMENTOS.PRESCRIÇAO(n_prescricao),
	FOREIGN KEY(n_registo, nome_comercial) 
	REFERENCES PRESCRIÇAO_MEDICAMENTOS.FARMACO(n_registo_farm, nome_comercial)
);
